<?php

declare(strict_types=1);

/*
 * TESTAREAAPISERVICELib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TESTAREAAPISERVICELib\Models;

use stdClass;

class BulkEditInvoiceRequest implements \JsonSerializable
{
    /**
     * @var Invoice[]
     */
    private $invoice;

    /**
     * @param Invoice[] $invoice
     */
    public function __construct(array $invoice)
    {
        $this->invoice = $invoice;
    }

    /**
     * Returns Invoice.
     *
     * @return Invoice[]
     */
    public function getInvoice(): array
    {
        return $this->invoice;
    }

    /**
     * Sets Invoice.
     *
     * @required
     * @maps invoice
     *
     * @param Invoice[] $invoice
     */
    public function setInvoice(array $invoice): void
    {
        $this->invoice = $invoice;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return mixed
     */
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['invoice'] = $this->invoice;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
