<?php

declare(strict_types=1);

/*
 * TESTAREAAPISERVICELib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TESTAREAAPISERVICELib\Models;

use stdClass;

class StoreInvoiceRequest2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $packageId;

    /**
     * @var Invoice[]
     */
    private $invoice;

    /**
     * @param string $packageId
     * @param Invoice[] $invoice
     */
    public function __construct(string $packageId, array $invoice)
    {
        $this->packageId = $packageId;
        $this->invoice = $invoice;
    }

    /**
     * Returns Package Id.
     */
    public function getPackageId(): string
    {
        return $this->packageId;
    }

    /**
     * Sets Package Id.
     *
     * @required
     * @maps package_id
     */
    public function setPackageId(string $packageId): void
    {
        $this->packageId = $packageId;
    }

    /**
     * Returns Invoice.
     *
     * @return Invoice[]
     */
    public function getInvoice(): array
    {
        return $this->invoice;
    }

    /**
     * Sets Invoice.
     *
     * @required
     * @maps invoice
     *
     * @param Invoice[] $invoice
     */
    public function setInvoice(array $invoice): void
    {
        $this->invoice = $invoice;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return mixed
     */
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['package_id'] = $this->packageId;
        $json['invoice']    = $this->invoice;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
