<?php

declare(strict_types=1);

/*
 * TESTAREAAPISERVICELib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TESTAREAAPISERVICELib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER_1 = 'Server 1';

    public const SERVER_2 = 'Server 2';
}
